// Event Action Types
export const ADD_EVENT = "ADD_EVENT";

// Chat Action Types
export const HANDLE_FILTER_USER = "HANDLE_FILTER_USER";
export const HANDLE_SELECT_USER = "HANDLE_SELECT_USER";
export const HANDLE_SEND_MESSAGE = "HANDLE_SEND_MESSAGE";

// Login Action Types
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_ERROR = "REQUEST_LOGIN_ERROR";

// Music Action Types
export const CHANGE_THEME_COLOR = "CHANGE_THEME_COLOR";
export const CHANGE_CURRENT_PLAYLIST = "CHANGE_CURRENT_PLAYLIST";